---
title: "Decision tree"
author: "SIDDARTH POOSALA"
date: "12/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
credit <- read.csv("e:\\credit.csv")
dim(credit)
str(credit)
table(credit$checking_balance)
summary(credit$months_loan_duration)

```
```{r}
set.seed(1234)
credit_rand<-credit[order(runif(1000)),]
head(credit)
head(credit_rand)
```

```{r}
head(credit$amount)
head(credit_rand$amount)
```


```{r}
summary(credit$amount)
summary(credit_rand$amount)
```
```{r}
credit_train <- credit_rand[1:900,]
credit_test <- credit_rand[901:1000,]
```

```{r}
prop.table(table(credit_train$default))
prop.table(table(credit_test$default))
```
```{r}
install.packages("c50")
library(c50)
```
```{r}
credit_train$default<-as.factor(credit_train$default)
str(credit_train$default)
credit_model <- C50::C5.0(credit_train[-17],credit_train$default[1:900] ,trials=10)
credit_model
summary(credit_model)

```
```{r}
credit_pred <- predict(credit_model,credit_test)
credit_pred

```
```{r}
library(gmodels)
CrossTable(credit_test$default,credit_pred,prop.chisq = FALSE,dnn = c('actual defult', 'predecited defult'))
```

